runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/multiselect-demo/index.html
  upload: dist/multiselect-demo/index.html

- url: /
  static_dir: dist/multiselect-demo

skip_files: 
- e2e/
- node_modules/
- src/
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^LICENSE